var paeiouIcons = [
    "swordfish",
    "pounder",
    "metal_generator",
    "adv_metal_generator",
    "andreas",
    "stalker",
    "rex",
    "aa_bot",
    "solar_cell",
    "anti_missile_tower",
	"tank_hover_adv",
	"adv_transport",
    "adv_heavy_bot",
    "anti_sub_ship",
    "naval_anti_orbital",
    "fab_tower",
    "adv_fab_tower",
    "metal_storage_adv",
    "energy_storage_adv",
    "l_mass_generator",
    "l_adv_mass_generator"
];
model.strategicIcons(model.strategicIcons().concat(paeiouIcons));